using System.Reflection;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace PTGOilSystem.Web.Services.AutoCode;

public sealed class AutoGeneratedCodeFilter : IAsyncActionFilter, IAsyncResultFilter
{
    private static readonly IReadOnlyDictionary<(string TypeName, string PropertyName), AutoCodeKind> Targets =
        new Dictionary<(string TypeName, string PropertyName), AutoCodeKind>()
        {
            [("Company", "Code")] = AutoCodeKind.Company,
            [("Partner", "Code")] = AutoCodeKind.Partner,
            [("Customer", "Code")] = AutoCodeKind.Customer,
            [("Supplier", "Code")] = AutoCodeKind.Supplier,
            [("Product", "Code")] = AutoCodeKind.Product,
            [("ExpenseType", "Code")] = AutoCodeKind.ExpenseType,
            [("Terminal", "Code")] = AutoCodeKind.Terminal,
            [("Location", "Code")] = AutoCodeKind.Location,
            [("Vessel", "Code")] = AutoCodeKind.Vessel,
            [("CashAccount", "Code")] = AutoCodeKind.CashAccount,
            [("ServiceProvider", "Code")] = AutoCodeKind.ServiceProvider,
            [("ServiceProviderCreateViewModel", "Code")] = AutoCodeKind.ServiceProvider,
            [("EmployeeFormViewModel", "EmployeeCode")] = AutoCodeKind.Employee,
            [("StorageTank", "TankCode")] = AutoCodeKind.StorageTank,
            [("OperationalAssetFormViewModel", "AssetCode")] = AutoCodeKind.OperationalAsset,
            [("ShipmentCreateViewModel", "ShipmentCode")] = AutoCodeKind.Shipment,
            [("SalesCreateViewModel", "InvoiceNumber")] = AutoCodeKind.SalesInvoice,
            [("DispatchDirectFromReceiptSaleCreateViewModel", "InvoiceNumber")] = AutoCodeKind.SalesInvoice,
            [("InventoryTransportReceiptCreateViewModel", "SaleInvoiceNumber")] = AutoCodeKind.SalesInvoice,
            [("InventoryTransportGroupOperationLegRow", "SaleInvoiceNumber")] = AutoCodeKind.SalesInvoice,
            [("LoadingReceiptCreateViewModel", "SaleInvoiceNumber")] = AutoCodeKind.SalesInvoice,
            [("LoadingReceiptAllocationLineInput", "SaleInvoiceNumber")] = AutoCodeKind.SalesInvoice
        };

    private readonly IAutoCodeService _autoCodes;

    public AutoGeneratedCodeFilter(IAutoCodeService autoCodes)
    {
        _autoCodes = autoCodes;
    }

    public async Task OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
    {
        if (IsCreateAction(context.RouteData.Values["action"]?.ToString()))
        {
            foreach (var argument in context.ActionArguments.Values)
            {
                await ApplyAsync(argument, context.ModelState, context.HttpContext.RequestAborted);
            }
        }

        await next();
    }

    public async Task OnResultExecutionAsync(ResultExecutingContext context, ResultExecutionDelegate next)
    {
        if (IsCreateAction(context.RouteData.Values["action"]?.ToString())
            && context.Result is ViewResult { Model: not null } view)
        {
            await ApplyAsync(view.Model, null, context.HttpContext.RequestAborted);
        }

        await next();
    }

    private async Task ApplyAsync(object? model, ModelStateDictionary? modelState, CancellationToken ct)
    {
        if (model is null)
        {
            return;
        }

        var generated = new Dictionary<AutoCodeKind, string>();
        await ApplyObjectAsync(model, modelState, generated, ct, depth: 0);
    }

    private async Task ApplyObjectAsync(
        object model,
        ModelStateDictionary? modelState,
        Dictionary<AutoCodeKind, string> generated,
        CancellationToken ct,
        int depth)
    {
        var modelType = model.GetType();
        foreach (var target in Targets)
        {
            if (!string.Equals(modelType.Name, target.Key.TypeName, StringComparison.Ordinal))
            {
                continue;
            }

            var property = modelType.GetProperty(target.Key.PropertyName, BindingFlags.Instance | BindingFlags.Public);
            if (property is null || property.PropertyType != typeof(string) || !property.CanWrite)
            {
                continue;
            }

            var value = await NextForRequestAsync(target.Value, generated, ct);
            property.SetValue(model, value);
            modelState?.Remove(target.Key.PropertyName);
        }

        if (depth >= 2)
        {
            return;
        }

        foreach (var property in modelType.GetProperties(BindingFlags.Instance | BindingFlags.Public))
        {
            if (property.PropertyType == typeof(string)
                || !typeof(System.Collections.IEnumerable).IsAssignableFrom(property.PropertyType))
            {
                continue;
            }

            if (property.GetValue(model) is not System.Collections.IEnumerable items)
            {
                continue;
            }

            var index = 0;
            foreach (var item in items)
            {
                if (item is null || item is string)
                {
                    index++;
                    continue;
                }

                await ApplyObjectAsync(item, modelState, generated, ct, depth + 1);
                index++;
            }
        }
    }

    private async Task<string> NextForRequestAsync(
        AutoCodeKind kind,
        Dictionary<AutoCodeKind, string> generated,
        CancellationToken ct)
    {
        if (!generated.TryGetValue(kind, out var current))
        {
            current = await _autoCodes.NextAsync(kind, ct);
        }
        else
        {
            current = Increment(current);
        }

        generated[kind] = current;
        return current;
    }

    private static string Increment(string code)
    {
        var split = code.Length;
        while (split > 0 && char.IsDigit(code[split - 1]))
        {
            split--;
        }

        if (split == code.Length)
        {
            return code + "001";
        }

        var prefix = code[..split];
        var digits = code[split..];
        var next = int.TryParse(digits, out var value) ? value + 1 : 1;
        return prefix + next.ToString(new string('0', digits.Length));
    }

    private static bool IsCreateAction(string? action)
        => !string.IsNullOrWhiteSpace(action)
            && action.StartsWith("Create", StringComparison.OrdinalIgnoreCase);
}
